### PR TITLE
Bypass easymap testing

### PR DESCRIPTION
**Pull request by tai271828**
In order to not confuse other developers, let's remove the useless legacy frontend folder of this codebase.

This pull request looks like a big trunk. No worries. It simply removes `frontend`. Pay your attention of the bonus commit instead.

Bonus commits: 1) enable the bar to trigger CI more frequently 2) Bypass easymap testing (see the commit log to check the rationale).

# Test this Pull Request
1. Enable the development environment as usual.
2. Make sure you can complete the reporting process and your backend receives API requests from the frontend.

# Expected Behavior
No function loss.

### CODE REVIEW

**Comment by EagleC0318** [comment]
Um, I didn't see the `frontend` is removed in this PR?

**Comment by tai271828** [comment]
> Um, I didn't see the `frontend` is removed in this PR?
Thanks for the comment. My apologies, I did not elaborate clearly: if you check the default branch `main-tbbca` of the current repository https://github.com/tai271828/disfactory-backend , there is no `frontend` folder already. You may also check our upstream still has the `frontend` folder https://github.com/Disfactory/Disfactory .

The day I removed `frontend` folder, the CI failure showed up. I thought the failure relates the removal of `frontend` folder. No, it did not. The error is raised for the unsupported easy map service https://github.com/Disfactory/Disfactory/pull/580 .

Let me edit the title of this pull request so people won't get confused again. : )

**Review by EagleC0318 — APPROVED** [review]
Looks fine for me.
Just wondering what is the behavior of the CI change.
Does that mean the CI auto test would be executed for all pushes and PRs (if the change isn't only on /docs)?
And what does the original  `branches: - "**"` mean? 
Thanks!

**Comment by tai271828** [comment]
> Looks fine for me. Just wondering what is the behavior of the CI change. Does that mean the CI auto test would be executed for all pushes and PRs (if the change isn't only on /docs)? And what does the original `branches: - "**"` mean? Thanks!

for all pushes and PRs --> yes

`branches: - "**"` means "for all branches" but it is redundant. By default, if no branch is specified, then all branches are applied.

**Comment by tai271828** [comment]
Thanks for the review!

**Pull request merged**
